"""sfc-ed1 대사창 가변 폭(VWF) — 공백·`. , ? !` 를 **반 칸(4px)** 으로 그린다(마스터 Q5, 2026-10-08).

배경: 대사창은 8px 타일 칸 17×4 배열이고 엔진이 글자마다 칸 번호를 하나 올린다. 반 칸 전진이면 칸 경계에 걸친 글자마다
(앞 글자 오른쪽 4px + 뒤 글자 왼쪽 4px) 타일이 따로 필요한데 미리 구우면 수천 종이다(devlog 10-08) — 그래서 **런타임에 합성**한다.

설계(훅 `hook`/`hookbuf` 가 글자를 내줄 때 한 곳에서):
  · 훅이 **px 커서 `V_VX`** 를 든다. 글자는 폭 `w`(8 또는 반각류 4)와 8×16 1bpp 그림(`V_G`)을 가진다.
  · **8px 글자가 칸 시작(off=0)에 오면 예전 길 그대로**(`alloc` — 글리프 캐시·슬롯 재사용) → 반각이 없는 줄은 바이트까지 같다.
  · 그 밖(반각이 칸을 시작하거나, off=4 위치)은 **합성 칸**: 슬롯 하나를 새로 받고 슬롯별 WRAM 버퍼(`BUF` + 슬롯×16B)에
    글자를 시프트해 OR 한 뒤 NMI 큐로 올린다(큐 항목 `Q_HI=$FF` = RAM 원본, `Q_LO` = 슬롯).
  · 새 칸이 생기지 않는 반각(off=4 에 4px)은 **엔진에 글자를 안 돌려주고 삼킨다** — 엔진은 칸 하나당 글자 하나만 센다.
  · 엔진 칸 번호(`$173B`)와 px 커서가 어긋나면(개행·페이지·창 지움·줄 올림) 칸 번호를 믿고 커서를 다시 맞춘다(`vwf_sync`).
버퍼 `$7E:E100~` 는 필드 이동·대사·메뉴에서 쓰기 0건을 쓰기 BP 로 확인한 구역이다(2026-10-08, status).
"""

BUF = 0x7EE100  # 슬롯별 합성 버퍼 — 16B(1bpp, 위 타일 8행 + 아래 타일 8행) × 슬롯
HALF_CODES = (0x10, 0x83, 0x84, 0x0C, 0x0F)  # 공백 · `.` · `,` · `!` · `?`


def emit(a, k):
    """`a` = Asm, `k` = 훅이 쓰는 주소·라벨 이름 모음(dict). 호출 규약: A 8비트 · X/Y 16비트(훅 본체와 같다)."""
    V_VX, V_VS, V_VD, V_VW, V_VO = k["V_VX"], k["V_VS"], k["V_VD"], k["V_VW"], k["V_VO"]
    V_VCELL, V_VT, V_VNC, V_VR, V_VCODE, V_VRSLOT, V_G = (
        k["V_VCELL"],
        k["V_VT"],
        k["V_VNC"],
        k["V_VR"],
        k["V_VCODE"],
        k["V_VRSLOT"],
        k["V_G"],
    )
    V_T0, V_T1, V_NEXT, V_HEAD = k["V_T0"], k["V_T1"], k["V_NEXT"], k["V_HEAD"]
    V_CTX, V_OVERFLOW, V_IDX = k["V_CTX"], k["V_OVERFLOW"], k["V_IDX"]
    V_OPEN, V_OCELL, V_NLF = k["V_OPEN"], k["V_OCELL"], k["V_NLF"]
    owner_lo, owner_hi, pin = k["owner_lo"], k["owner_hi"], k["pin"]
    Q_SLOT, Q_LO, Q_HI, Q_CTX = k["Q_SLOT"], k["Q_LO"], k["Q_HI"], k["Q_CTX"]
    nslot, QN, GLYPH_BASE = k["nslot"], k["QN"], k["GLYPH_BASE"]
    G16 = V_G & 0xFFFF  # 뱅크 $7E 안의 16비트 주소 — DBR=$7E 로 바꿔 abs,Y 로 읽는다

    def lm(op, addr):
        a.op(op, addr=addr, mode="long")

    # ── 칸 번호와 px 커서 맞추기 ────────────────────────────────────────────────
    # 나갈 때: V_VT = 엔진이 **다음에 쓸 칸** · V_VCELL = 커서가 가리키는 칸 · V_VO = 칸 안 위치(0 | 4)
    a.label("vwf_sync")
    a.phx()
    a.sep(imm=0x20)
    lm("lda", V_OPEN)  # 크롤(오프닝·엔딩)은 자기 칸 카운터, 대사 엔진은 `$173B`
    a.beq(label="vsy_d")
    lm("lda", V_OCELL)
    a.bra(label="vsy_c")
    a.label("vsy_d")
    lm("lda", 0x00173B)
    a.label("vsy_c")
    a.inc()
    lm("sta", V_VT)
    a.rep(imm=0x20)
    lm("lda", V_VX)
    a.lsr()
    a.lsr()
    a.lsr()
    a.sep(imm=0x20)
    lm("sta", V_VCELL)
    lm("lda", V_VX)
    a.op("and", imm=0x07)
    lm("sta", V_VO)
    a.beq(label="vsy_al")
    lm("lda", V_VT)  # 칸 안 중간이면 그 칸이 엔진의 「마지막으로 쓴 칸」이어야 한다
    a.dec()
    lm("cmp", V_VCELL)
    a.beq(label="vsy_ok")
    a.bra(label="vsy_reset")
    a.label("vsy_al")
    lm("lda", V_VT)
    lm("cmp", V_VCELL)
    a.beq(label="vsy_ok")
    a.label("vsy_reset")
    a.rep(imm=0x20)
    lm("lda", V_VT)
    a.op("and", imm=0x00FF, m16=True)
    a.asl()
    a.asl()
    a.asl()
    lm("sta", V_VX)
    a.sep(imm=0x20)
    lm("lda", V_VT)
    lm("sta", V_VCELL)
    a.lda(imm=0x00)
    lm("sta", V_VO)
    a.label("vsy_ok")
    a.plx()
    a.rts()

    # ── 합성 칸용 슬롯 하나 (캐시를 안 쓴다 — 오너를 $FFFF 로) → A = 슬롯 번호 ───────────
    # ── 슬롯이 화면에 살아 있나 (X = 슬롯, 16비트) → C=1 이면 창 칸 배열(`$0305`, 17×4)이 그 슬롯의 코드를 쓴다 ──
    # 🔴 라운드로빈은 「가장 오래 할당된 슬롯」을 내주는데, 합성 칸은 칸마다 슬롯 하나를 새로 먹어(캐시 불가) 전투 로그처럼
    #    길게 쌓이는 창에서는 **아직 화면에 있는 칸이 한 바퀴 돌아 덮였다**(2026-10-08 실측 — 로그 첫 줄 머리가 끝 글자로 바뀜).
    #    살아 있는 칸은 건너뛴다. 칸 배열은 68바이트라 한 번에 훑는다.
    a.label("vwf_live")
    a.op("lda", addr="slot_code", mode="absx")
    a.ldx(imm=0x0000, m16=True)
    a.label("vl_l")
    a.op("cmp", addr=0x000305, mode="longx")
    a.beq(label="vl_y")
    a.inx()
    a.cpx(imm=68, m16=True)
    a.bne(label="vl_l")
    a.clc()
    a.rts()
    a.label("vl_y")
    a.sec()
    a.rts()

    a.label("vwf_newslot")
    a.lda(imm=nslot)
    lm("sta", V_T0)
    a.label("vn_try")
    lm("lda", V_NEXT)
    a.cmp(imm=nslot)
    a.bcc(label="vn_t0")
    a.lda(imm=0x00)
    lm("sta", V_NEXT)
    a.label("vn_t0")
    a.rep(imm=0x20)
    a.op("and", imm=0x00FF, m16=True)
    a.tax()
    a.sep(imm=0x20)
    if k["xfrom"] < nslot:  # 크롤 전용 슬롯은 인게임에서 건너뛴다(`hook.alloc` 과 같은 규칙)
        a.cpx(imm=k["xfrom"], m16=True)
        a.bcc(label="vn_nx")
        lm("lda", V_CTX)
        a.cmp(imm=0x01)
        a.bne(label="vn_skip")
        a.label("vn_nx")
    a.op("lda", addr=pin, mode="longx")
    a.bne(label="vn_skip")
    a.jsr(addr="vwf_live", mode="abs")  # 지금 창 칸 배열이 쓰는 슬롯이면 건너뛴다
    a.bcc(label="vn_take")
    a.label("vn_skip")
    lm("lda", V_NEXT)
    a.inc()
    lm("sta", V_NEXT)
    lm("lda", V_T0)
    a.dec()
    lm("sta", V_T0)
    a.bne(label="vn_try")
    a.label("vn_take")
    lm("lda", V_NEXT)
    a.cmp(imm=nslot)
    a.bcc(label="vn0")
    a.lda(imm=0x00)
    a.label("vn0")
    lm("sta", V_T1)
    a.inc()
    a.cmp(imm=nslot)
    a.bcc(label="vn1")
    a.lda(imm=0x01)
    lm("sta", V_OVERFLOW)
    a.lda(imm=0x00)
    a.label("vn1")
    lm("sta", V_NEXT)
    lm("lda", V_T1)
    a.rep(imm=0x20)
    a.op("and", imm=0x00FF, m16=True)
    a.tax()
    a.sep(imm=0x20)
    a.lda(imm=0xFF)
    a.op("sta", addr=owner_lo, mode="longx")
    a.op("sta", addr=owner_hi, mode="longx")
    lm("lda", V_T1)
    a.rts()

    # ── 슬롯 버퍼 16B 를 0 으로 (A = 슬롯) ────────────────────────────────────────
    a.label("vwf_clrbuf")
    a.rep(imm=0x20)
    a.op("and", imm=0x00FF, m16=True)
    a.asl()
    a.asl()
    a.asl()
    a.asl()
    a.tax()
    a.sep(imm=0x20)
    a.lda(imm=0x00)
    a.ldy(imm=0x0010, m16=True)
    a.label("vc_l")
    a.op("sta", addr=BUF, mode="longx")
    a.inx()
    a.dey()
    a.bne(label="vc_l")
    a.rts()

    # ── 글자 그림 → 슬롯 버퍼에 OR (V_VRSLOT = 슬롯) ───────────────────────────────
    # 세 변종: 그대로 / 오른쪽으로 4(칸 오른쪽 절반) / 왼쪽으로 4(칸 넘침 몫)
    for name, shifts in (("vwf_blit0", None), ("vwf_blit1", "lsr"), ("vwf_blit2", "asl")):
        a.label(name)
        a.rep(imm=0x20)
        lm("lda", V_VRSLOT)
        a.op("and", imm=0x00FF, m16=True)
        a.asl()
        a.asl()
        a.asl()
        a.asl()
        a.clc()
        a.op("adc", imm=BUF & 0xFFFF, m16=True)
        a.tax()
        a.sep(imm=0x20)
        a.phb()
        a.lda(imm=0x7E)
        a.pha()
        a.plb()
        a.ldy(imm=0x0000, m16=True)
        a.label(name + "_l")
        a.op("lda", addr=G16, mode="absy")
        if shifts:
            for _ in range(4):
                getattr(a, shifts)()
        a.op("ora", addr=0x0000, mode="absx")
        a.op("sta", addr=0x0000, mode="absx")
        a.inx()
        a.iny()
        a.cpy(imm=0x0010, m16=True)
        a.bne(label=name + "_l")
        a.plb()
        a.rts()

    # ── 업로드 큐에 「RAM 원본 슬롯」 항목을 넣는다 (A = 슬롯) ─────────────────────────
    a.label("vwf_enq")
    a.phx()
    lm("sta", V_T1)  # 본체 임시 — 이 함수가 끝나면 필요 없다
    lm("lda", V_HEAD)
    a.rep(imm=0x20)
    a.op("and", imm=0x00FF, m16=True)
    a.tax()
    a.sep(imm=0x20)
    lm("lda", V_T1)
    a.op("sta", addr=Q_SLOT, mode="longx")
    a.op("sta", addr=Q_LO, mode="longx")
    a.lda(imm=0xFF)  # 글리프 색인 상위로는 절대 안 나오는 값 = RAM 원본 표지
    a.op("sta", addr=Q_HI, mode="longx")
    lm("lda", V_CTX)
    a.op("sta", addr=Q_CTX, mode="longx")
    lm("lda", V_HEAD)
    a.inc()
    a.op("and", imm=QN - 1)
    lm("sta", V_HEAD)
    a.plx()
    a.rts()

    # ── 글자 그림 읽기 → V_G[16] ─────────────────────────────────────────────────
    # 한글(V_IDX = 글리프 색인): 글리프 뱅크 32B/자(평면0·평면1 번갈아) → 평면0 만 16행
    a.label("vwf_ldg_h")
    a.rep(imm=0x20)
    lm("lda", V_IDX)
    for _ in range(5):
        a.asl()
    a.tax()
    a.sep(imm=0x20)
    a.phb()
    a.lda(imm=0x7E)
    a.pha()
    a.plb()
    a.ldy(imm=0x0000, m16=True)
    a.label("lgh_l")
    a.op("lda", addr=GLYPH_BASE, mode="longx")
    a.op("sta", addr=G16, mode="absy")
    a.inx()
    a.inx()
    a.iny()
    a.cpy(imm=0x0010, m16=True)
    a.bne(label="lgh_l")
    a.plb()
    a.rts()
    # 원본 1바이트 글자(V_VR = 코드): 훅 뱅크의 `rawtab` 16B/자
    a.label("vwf_ldg_r")
    a.rep(imm=0x20)
    lm("lda", V_VR)
    a.op("and", imm=0x00FF, m16=True)
    a.asl()
    a.asl()
    a.asl()
    a.asl()
    a.tax()
    a.sep(imm=0x20)
    a.phb()
    a.lda(imm=0x7E)
    a.pha()
    a.plb()
    a.ldy(imm=0x0000, m16=True)
    a.label("lgr_l")
    a.op("lda", addr="rawtab", mode="longx")
    a.op("sta", addr=G16, mode="absy")
    a.inx()
    a.iny()
    a.cpy(imm=0x0010, m16=True)
    a.bne(label="lgr_l")
    a.plb()
    a.rts()

    # ── 커서를 V_VW 만큼 옮기고, 만든 칸이 68번째면 엔진의 줄 올림(−17칸 = −136px)을 따라간다 ──
    # 들어올 때 V_VNC = 이번에 **새로 만든 칸**의 번호
    a.label("vwf_adv")
    a.lda(imm=0x00)
    lm("sta", V_NLF)  # 줄 첫 글자가 나갔다 — 명시 개행 표지를 푼다
    a.rep(imm=0x20)
    lm("lda", V_VW)
    a.op("and", imm=0x00FF, m16=True)
    a.clc()
    a.op("adc", addr=V_VX, mode="long")
    lm("sta", V_VX)
    a.sep(imm=0x20)
    lm("lda", V_VNC)
    a.cmp(imm=0x44)
    a.bne(label="va_ok")
    a.rep(imm=0x20)
    lm("lda", V_VX)
    a.sec()
    a.op("sbc", imm=136, m16=True)
    lm("sta", V_VX)
    a.sep(imm=0x20)
    a.label("va_ok")
    a.rts()

    # ── 합성 칸에 글자를 얹는다 (V_G 에 그림, V_VW = 4|8, vwf_sync 를 마친 뒤) ───────────
    # 돌려줌: C=0 → A = 엔진에 줄 슬롯 코드 / C=1 → 삼킴(새 칸이 없다)
    a.label("vwf_put")
    lm("lda", V_VO)
    a.bne(label="vp_mid")
    # off=0 — 새 칸. 반각(4px)만 온다(8px 는 예전 길로 갔다)
    a.jsr(addr="vwf_flush", mode="abs")  # 앞 칸이 바뀐 채 안 올라갔으면 지금 올린다(한 훅 호출 안에서 삼킨 글자가 이어졌을 때)
    a.jsr(addr="vwf_newslot", mode="abs")
    lm("sta", V_VS)
    a.jsr(addr="vwf_clrbuf", mode="abs")
    lm("lda", V_VS)
    lm("sta", V_VRSLOT)
    a.jsr(addr="vwf_blit0", mode="abs")
    a.lda(imm=0x01)
    lm("sta", V_VD)
    lm("lda", V_VCELL)
    lm("sta", V_VNC)
    a.jsr(addr="vwf_adv", mode="abs")
    a.jmp(addr="vp_code", mode="abs")
    a.label("vp_mid")  # off=4 — 지금 칸의 오른쪽 절반을 채운다
    lm("lda", V_VW)
    a.cmp(imm=0x04)
    a.beq(label="vp_fit")
    a.jmp(addr="vp_spill", mode="abs")
    a.label("vp_fit")
    lm("lda", V_VS)
    lm("sta", V_VRSLOT)
    a.jsr(addr="vwf_blit1", mode="abs")
    a.lda(imm=0x01)
    lm("sta", V_VD)
    a.rep(imm=0x20)
    lm("lda", V_VX)
    a.clc()
    a.op("adc", imm=4, m16=True)
    lm("sta", V_VX)
    a.sep(imm=0x20)
    a.sec()  # 새 칸 없음 → 삼킨다
    a.rts()
    a.label("vp_spill")  # 8px 글자가 칸 경계를 넘는다: 앞 칸을 마저 채우고 새 칸을 연다
    lm("lda", V_VS)
    lm("sta", V_VRSLOT)
    a.jsr(addr="vwf_blit1", mode="abs")
    lm("lda", V_VS)
    a.jsr(addr="vwf_enq", mode="abs")  # 이 칸은 이제 끝났다 — 마지막 모양을 올린다
    a.jsr(addr="vwf_newslot", mode="abs")
    lm("sta", V_VS)
    a.jsr(addr="vwf_clrbuf", mode="abs")
    lm("lda", V_VS)
    lm("sta", V_VRSLOT)
    a.jsr(addr="vwf_blit2", mode="abs")
    a.lda(imm=0x01)
    lm("sta", V_VD)
    lm("lda", V_VCELL)
    a.inc()
    lm("sta", V_VNC)
    a.jsr(addr="vwf_adv", mode="abs")
    a.label("vp_code")
    lm("lda", V_VS)
    a.rep(imm=0x20)
    a.op("and", imm=0x00FF, m16=True)
    a.tax()
    a.sep(imm=0x20)
    a.op("lda", addr="slot_code", mode="absx")
    a.clc()
    a.rts()

    # ── 크롤 줄바꿈·쪽 바뀜: 지금 칸을 올리고 px 커서·칸 번호를 줄 처음으로 ──────────────────
    a.label("vwf_crawl_nl")
    a.jsr(addr="vwf_flush", mode="abs")
    a.rep(imm=0x20)
    a.lda(imm=0x0000, m16=True)
    lm("sta", V_VX)
    a.sep(imm=0x20)
    a.lda(imm=0xFF)
    lm("sta", V_OCELL)
    a.rts()

    # ── 훅을 나가기 전: 바뀐 지금 칸의 모양을 큐에 올린다 ───────────────────────────────
    a.label("vwf_flush")
    lm("lda", V_VD)
    a.beq(label="vf_ret")
    a.lda(imm=0x00)
    lm("sta", V_VD)
    lm("lda", V_VS)
    a.jsr(addr="vwf_enq", mode="abs")
    a.label("vf_ret")
    a.rts()

    # ── 입구 1: 한글 글리프(V_IDX) ────────────────────────────────────────────────
    # 돌려줌: C=0 → A = 엔진에 줄 코드 · C=1 → 삼킴(한글은 8px 라 삼키는 일은 없다)
    a.label("vwf_glyph")
    a.jsr(addr="vwf_sync", mode="abs")
    lm("lda", V_VO)
    a.bne(label="vg_mis")
    a.jsr(addr="alloc", mode="abs")  # 칸 시작의 8px — 예전 길(글리프 캐시)
    lm("sta", V_VCODE)
    lm("lda", V_VCELL)
    lm("sta", V_VNC)
    a.lda(imm=0x08)
    lm("sta", V_VW)
    a.jsr(addr="vwf_adv", mode="abs")
    lm("lda", V_VCODE)
    a.clc()
    a.rts()
    a.label("vg_mis")
    a.jsr(addr="vwf_ldg_h", mode="abs")
    a.lda(imm=0x08)
    lm("sta", V_VW)
    a.jmp(addr="vwf_put", mode="abs")

    # ── 입구 2: 원본 1바이트 글자(X = 코드 < $CF) ─────────────────────────────────
    a.label("vwf_raw")
    a.txa()
    lm("sta", V_VR)
    a.jsr(addr="vwf_sync", mode="abs")
    # 오프닝·엔딩(컨텍스트 1)의 숫자는 **늘 우리 글꼴 4px 반각 합성**으로(마스터 10-08 「얇은 반각이 더 일관성 있다」). 칸 시작이면 원판 시트의
    # 굵은 숫자 타일이, 칸 중간이면 합성 칸의 가는 숫자가 나가 한 문장 안에서 꼴이 섞였고 「1 0」 처럼 벌어졌다. 인게임(0)은 그대로.
    lm("lda", V_VR)
    a.cmp(imm=0x0A)
    a.bcs(label="vr_nd")
    lm("lda", V_CTX)
    a.cmp(imm=0x01)
    a.bne(label="vr_nd")
    a.jsr(addr="vwf_ldg_r", mode="abs")
    a.lda(imm=0x04)
    lm("sta", V_VW)  # 우리 글꼴 숫자(4px 폭)를 반각 칸으로 — 「10」이 붙는다
    a.jmp(addr="vwf_put", mode="abs")
    a.label("vr_nd")
    lm("lda", V_VR)
    a.cmp(imm=0x10)
    a.beq(label="vr_sp")
    for code in HALF_CODES[1:]:
        a.cmp(imm=code)
        a.beq(label="vr_h1")
    lm("lda", V_VO)
    a.bne(label="vr_fm")
    a.label("vr_pass")  # 칸 시작의 8px 원본 글자 — 그대로 내준다(타일은 시트에 있다)
    lm("lda", V_VCELL)
    lm("sta", V_VNC)
    a.lda(imm=0x08)
    lm("sta", V_VW)
    a.jsr(addr="vwf_adv", mode="abs")
    lm("lda", V_VR)
    a.clc()
    a.rts()
    a.label("vr_h1")  # `beq` 가 멀어 가까운 징검다리를 둔다
    a.jmp(addr="vr_half", mode="abs")
    a.label("vr_fm")  # off=4 에 오는 8px 원본 글자 — 그림이 있으면 합성, 없으면 칸 경계로 맞춘다
    lm("lda", V_VR)
    a.rep(imm=0x20)
    a.op("and", imm=0x00FF, m16=True)
    a.tax()
    a.sep(imm=0x20)
    a.op("lda", addr="rawvalid", mode="absx")
    a.beq(label="vr_snap")
    a.jsr(addr="vwf_ldg_r", mode="abs")
    a.lda(imm=0x08)
    lm("sta", V_VW)
    a.jmp(addr="vwf_put", mode="abs")
    a.label("vr_snap")
    a.rep(imm=0x20)
    lm("lda", V_VX)
    a.clc()
    a.op("adc", imm=7, m16=True)
    a.op("and", imm=0xFFF8, m16=True)
    lm("sta", V_VX)
    a.lsr()
    a.lsr()
    a.lsr()
    a.sep(imm=0x20)
    lm("sta", V_VCELL)
    a.jmp(addr="vr_pass", mode="abs")
    a.label("vr_sp")  # 공백 — 줄 첫 칸이면 건너뛴다(마스터 판정 2026-09-27④). 크롤은 손으로 맞춘 줄이라 건너뛰지 않는다
    lm("lda", V_VO)
    a.bne(label="vr_hfar")
    lm("lda", V_OPEN)
    a.bne(label="vr_hfar")
    lm("lda", V_NLF)
    a.beq(label="vr_sp2")
    a.label("vr_hfar")
    a.jmp(addr="vr_half", mode="abs")
    a.label("vr_sp2")
    lm("lda", V_VT)
    a.beq(label="vr_skip")
    a.cmp(imm=17)
    a.beq(label="vr_skip")
    a.cmp(imm=34)
    a.beq(label="vr_skip")
    a.cmp(imm=51)
    a.beq(label="vr_skip")
    a.label("vr_half")
    a.jsr(addr="vwf_ldg_r", mode="abs")
    a.lda(imm=0x04)
    lm("sta", V_VW)
    a.jmp(addr="vwf_put", mode="abs")
    a.label("vr_skip")
    a.sec()
    a.rts()


def rawtab(tbl: dict[str, int], render) -> tuple[bytes, bytes]:
    """원본 1바이트 코드(0..$CE) → 16B 1bpp 그림 표(`rawtab`)와 「그림이 있나」 표(`rawvalid`, 256B).
    `tbl` = {글자: 코드}(인코더의 `KR_TABLE`), `render(ch)` = 16행 정수 목록."""
    pics = {}
    for ch, code in tbl.items():
        if code >= 0xCF or ch == "\n":
            continue
        pics[code] = bytes(render(ch)) if ch != " " else bytes(16)
    rt = bytearray(0xCF * 16)
    valid = bytearray(256)
    for code, pic in pics.items():
        rt[code * 16 : code * 16 + 16] = pic
        valid[code] = 1
    return bytes(rt), bytes(valid)
