"""sfc-ed1 대사창 가변 폭(VWF) — 공백·`. , ? !` 를 **반 칸(4px)** 으로 그린다(마스터 Q5, 2026-10-08).

배경: 대사창은 8px 타일 칸 17×4 배열이고 엔진이 글자마다 칸 번호를 하나 올린다. 반 칸 전진이면 칸 경계에 걸친 글자마다
(앞 글자 오른쪽 4px + 뒤 글자 왼쪽 4px) 타일이 따로 필요한데 미리 구우면 수천 종이다(devlog 10-08) — 그래서 **런타임에 합성**한다.

설계(훅 `hook`/`hookbuf` 가 글자를 내줄 때 한 곳에서):
  · 훅이 **px 커서 `V_VX`** 를 든다. 글자는 폭 `w`(8 또는 반각류 4)와 8×16 1bpp 그림(`V_G`)을 가진다.
  · **8px 글자가 칸 시작(off=0)에 오면 예전 길 그대로**(`alloc` — 글리프 캐시·슬롯 재사용) → 반각이 없는 줄은 바이트까지 같다.
  · 그 밖(반각이 칸을 시작하거나, off=4 위치)은 **합성 칸**: 슬롯 하나를 새로 받고 슬롯별 WRAM 버퍼(`BUF` + 슬롯×16B)에
    글자를 시프트해 OR 한 뒤 NMI 큐로 올린다(큐 항목 `Q_HI=$FF` = RAM 원본, `Q_LO` = 슬롯).
  · 새 칸이 생기지 않는 반각(off=4 에 4px)은 **엔진에 글자를 안 돌려주고 삼킨다** — 엔진은 칸 하나당 글자 하나만 센다.
  · 엔진 칸 번호(`$173B`)와 px 커서가 어긋나면(개행·페이지·창 지움·줄 올림) 칸 번호를 믿고 커서를 다시 맞춘다(`vwf_sync`).
버퍼 `$7E:E100~` 는 필드 이동·대사·메뉴에서 쓰기 0건을 쓰기 BP 로 확인한 구역이다(2026-10-08, status).
"""

BUF = 0x7EE100  # 슬롯별 합성 버퍼 — 16B(1bpp, 위 타일 8행 + 아래 타일 8행) × 슬롯
HALF_CODES = (0x10, 0x83, 0x84, 0x0C, 0x0F)  # 공백 · `.` · `,` · `!` · `?`
# 같은 몬스터가 여럿일 때 엔진이 이름 뒤에 붙이는 A~D(`$02:E0CE` 표) — 마스터 10-09 「ABCD 도 반각」: 우리 글꼴 4px 합성으로
LETTER_CODES = (0xC3, 0xC4, 0x8F, 0x8E)


def emit(a, k):
    """`a` = Asm, `k` = 훅이 쓰는 주소·라벨 이름 모음(dict). 호출 규약: A 8비트 · X/Y 16비트(훅 본체와 같다)."""
    V_VX, V_VS, V_VD, V_VW, V_VO = k["V_VX"], k["V_VS"], k["V_VD"], k["V_VW"], k["V_VO"]
    V_SH = k["V_SH"]
    V_VCELL, V_VT, V_VNC, V_VR, V_VCODE, V_VRSLOT, V_G = (
        k["V_VCELL"],
        k["V_VT"],
        k["V_VNC"],
        k["V_VR"],
        k["V_VCODE"],
        k["V_VRSLOT"],
        k["V_G"],
    )
    V_T0, V_T1, V_NEXT, V_HEAD = k["V_T0"], k["V_T1"], k["V_NEXT"], k["V_HEAD"]
    V_CTX, V_OVERFLOW, V_IDX = k["V_CTX"], k["V_OVERFLOW"], k["V_IDX"]
    V_OPEN, V_OCELL, V_NLF = k["V_OPEN"], k["V_OCELL"], k["V_NLF"]
    V_WM = k["V_WM"]
    owner_lo, owner_hi, pin = k["owner_lo"], k["owner_hi"], k["pin"]
    Q_SLOT, Q_LO, Q_HI, Q_CTX = k["Q_SLOT"], k["Q_LO"], k["Q_HI"], k["Q_CTX"]
    nslot, QN, GLYPH_BASE = k["nslot"], k["QN"], k["GLYPH_BASE"]
    G16 = V_G & 0xFFFF  # 뱅크 $7E 안의 16비트 주소 — DBR=$7E 로 바꿔 abs,Y 로 읽는다

    def lm(op, addr):
        a.op(op, addr=addr, mode="long")

    # ── 칸 번호와 px 커서 맞추기 ────────────────────────────────────────────────
    # 나갈 때: V_VT = 엔진이 **다음에 쓸 칸** · V_VCELL = 커서가 가리키는 칸 · V_VO = 칸 안 위치(0 | 4)
    a.label("vwf_sync")
    a.phx()
    a.sep(imm=0x20)
    lm("lda", V_OPEN)  # 크롤(오프닝·엔딩)은 자기 칸 카운터, 대사 엔진은 `$173B`
    a.beq(label="vsy_d")
    lm("lda", V_OCELL)
    a.bra(label="vsy_c")
    a.label("vsy_d")
    lm("lda", 0x00173B)
    a.label("vsy_c")
    a.inc()
    lm("sta", V_VT)
    a.rep(imm=0x20)
    lm("lda", V_VX)
    a.lsr()
    a.lsr()
    a.lsr()
    a.sep(imm=0x20)
    lm("sta", V_VCELL)
    lm("lda", V_VX)
    a.op("and", imm=0x07)
    lm("sta", V_VO)
    a.beq(label="vsy_al")
    lm("lda", V_VT)  # 칸 안 중간이면 그 칸이 엔진의 「마지막으로 쓴 칸」이어야 한다
    a.dec()
    lm("cmp", V_VCELL)
    a.beq(label="vsy_ok")
    a.bra(label="vsy_reset")
    a.label("vsy_al")
    lm("lda", V_VT)
    lm("cmp", V_VCELL)
    a.beq(label="vsy_ok")
    a.label("vsy_reset")
    a.rep(imm=0x20)
    lm("lda", V_VT)
    a.op("and", imm=0x00FF, m16=True)
    a.asl()
    a.asl()
    a.asl()
    lm("sta", V_VX)
    a.sep(imm=0x20)
    lm("lda", V_VT)
    lm("sta", V_VCELL)
    a.lda(imm=0x00)
    lm("sta", V_VO)
    a.label("vsy_ok")
    a.plx()
    a.rts()

    # ── 합성 칸용 슬롯 하나 (캐시를 안 쓴다 — 오너를 $FFFF 로) → A = 슬롯 번호 ───────────
    # ── 슬롯이 화면에 살아 있나 (X = 슬롯, 16비트) → C=1 이면 창 칸 배열(`$0305`, 17×4)이 그 슬롯의 코드를 쓴다 ──
    # 🔴 라운드로빈은 「가장 오래 할당된 슬롯」을 내주는데, 합성 칸은 칸마다 슬롯 하나를 새로 먹어(캐시 불가) 전투 로그처럼
    #    길게 쌓이는 창에서는 **아직 화면에 있는 칸이 한 바퀴 돌아 덮였다**(2026-10-08 실측 — 로그 첫 줄 머리가 끝 글자로 바뀜).
    #    살아 있는 칸은 건너뛴다. 칸 배열은 68바이트라 한 번에 훑는다.
    a.label("vwf_live")
    a.op("lda", addr="slot_code", mode="absx")
    a.ldx(imm=0x0000, m16=True)
    a.label("vl_l")
    a.op("cmp", addr=0x000305, mode="longx")
    a.beq(label="vl_y")
    a.inx()
    a.cpx(imm=68, m16=True)
    a.bne(label="vl_l")
    a.clc()
    a.rts()
    a.label("vl_y")
    a.sec()
    a.rts()

    a.label("vwf_newslot")
    a.lda(imm=nslot)
    lm("sta", V_T0)
    a.label("vn_try")
    lm("lda", V_NEXT)
    a.cmp(imm=nslot)
    a.bcc(label="vn_t0")
    a.lda(imm=0x00)
    lm("sta", V_NEXT)
    a.label("vn_t0")
    a.rep(imm=0x20)
    a.op("and", imm=0x00FF, m16=True)
    a.tax()
    a.sep(imm=0x20)
    if k["xfrom"] < nslot:  # 크롤 전용 슬롯은 인게임에서 건너뛴다(`hook.alloc` 과 같은 규칙)
        a.cpx(imm=k["xfrom"], m16=True)
        a.bcc(label="vn_nx")
        lm("lda", V_CTX)
        a.cmp(imm=0x01)
        a.bne(label="vn_skip")
        a.label("vn_nx")
    a.op("lda", addr=pin, mode="longx")
    a.bne(label="vn_skip")
    a.jsr(addr="vwf_live", mode="abs")  # 지금 창 칸 배열이 쓰는 슬롯이면 건너뛴다
    a.bcc(label="vn_take")
    a.label("vn_skip")
    lm("lda", V_NEXT)
    a.inc()
    lm("sta", V_NEXT)
    lm("lda", V_T0)
    a.dec()
    lm("sta", V_T0)
    a.bne(label="vn_try")
    a.label("vn_take")
    lm("lda", V_NEXT)
    a.cmp(imm=nslot)
    a.bcc(label="vn0")
    a.lda(imm=0x00)
    a.label("vn0")
    lm("sta", V_T1)
    a.inc()
    a.cmp(imm=nslot)
    a.bcc(label="vn1")
    a.lda(imm=0x01)
    lm("sta", V_OVERFLOW)
    a.lda(imm=0x00)
    a.label("vn1")
    lm("sta", V_NEXT)
    lm("lda", V_T1)
    a.rep(imm=0x20)
    a.op("and", imm=0x00FF, m16=True)
    a.tax()
    a.sep(imm=0x20)
    a.lda(imm=0xFF)
    a.op("sta", addr=owner_lo, mode="longx")
    a.op("sta", addr=owner_hi, mode="longx")
    lm("lda", V_T1)
    a.rts()

    # ── 슬롯 버퍼 16B 를 0 으로 (A = 슬롯) ────────────────────────────────────────
    a.label("vwf_clrbuf")
    a.rep(imm=0x20)
    a.op("and", imm=0x00FF, m16=True)
    a.asl()
    a.asl()
    a.asl()
    a.asl()
    a.tax()
    a.sep(imm=0x20)
    a.lda(imm=0x00)
    a.ldy(imm=0x0010, m16=True)
    a.label("vc_l")
    a.op("sta", addr=BUF, mode="longx")
    a.inx()
    a.dey()
    a.bne(label="vc_l")
    a.rts()

    # ── 글자 그림 → 슬롯 버퍼에 OR (V_VRSLOT = 슬롯, V_SH = 시프트 0~7) ─────────────────────────────
    # 가변 폭이라 글자가 칸 안 **어느 열에서나**(0~7) 시작한다 — 그림을 오른쪽으로 V_SH(현재 칸에 걸치는 몫) 또는
    # 왼쪽으로 V_SH(다음 칸으로 넘치는 몫, = 8 − 시작 열) 민다. 행 루프 안에서 횟수를 세면 레지스터가 모자라
    # 시프트 횟수마다 본체를 따로 둔다(`vbR0~7` · `vbL1~7`, 조립 때 만든다).
    for d, op, rng in (("R", "lsr", range(8)), ("L", "asl", range(1, 8))):
        a.label(f"vwf_blit{d}")
        lm("lda", V_SH)
        for n in rng:
            if n == 0:
                continue
            a.cmp(imm=n)
            a.bne(label=f"vd{d}{n}")
            a.jsr(addr=f"vb{d}{n}", mode="abs")
            a.bra(label=f"vx{d}")
            a.label(f"vd{d}{n}")
        if d == "R":
            a.jsr(addr="vbR0", mode="abs")  # V_SH = 0
        a.label(f"vx{d}")  # L 0 은 없다(넘칠 몫이 없다) — 그대로 나간다
        a.rts()
        for n in rng:
            name = f"vb{d}{n}"
            a.label(name)
            a.rep(imm=0x20)
            lm("lda", V_VRSLOT)
            a.op("and", imm=0x00FF, m16=True)
            a.asl()
            a.asl()
            a.asl()
            a.asl()
            a.clc()
            a.op("adc", imm=BUF & 0xFFFF, m16=True)
            a.tax()
            a.sep(imm=0x20)
            a.phb()
            a.lda(imm=0x7E)
            a.pha()
            a.plb()
            a.ldy(imm=0x0000, m16=True)
            a.label(name + "_l")
            a.op("lda", addr=G16, mode="absy")
            for _ in range(n):
                getattr(a, op)()
            a.op("ora", addr=0x0000, mode="absx")
            a.op("sta", addr=0x0000, mode="absx")
            a.inx()
            a.iny()
            a.cpy(imm=0x0010, m16=True)
            a.bne(label=name + "_l")
            a.plb()
            a.rts()

    # ── 업로드 큐에 「RAM 원본 슬롯」 항목을 넣는다 (A = 슬롯) ─────────────────────────
    a.label("vwf_enq")
    a.phx()
    lm("sta", V_T1)  # 본체 임시 — 이 함수가 끝나면 필요 없다
    a.jsr(addr="q_wait", mode="abs")  # 큐가 가득이면 기다린다(`hook.q_wait`)
    lm("lda", V_HEAD)
    a.rep(imm=0x20)
    a.op("and", imm=0x00FF, m16=True)
    a.tax()
    a.sep(imm=0x20)
    lm("lda", V_T1)
    a.op("sta", addr=Q_SLOT, mode="longx")
    a.op("sta", addr=Q_LO, mode="longx")
    a.lda(imm=0xFF)  # 글리프 색인 상위로는 절대 안 나오는 값 = RAM 원본 표지
    a.op("sta", addr=Q_HI, mode="longx")
    lm("lda", V_CTX)
    a.op("sta", addr=Q_CTX, mode="longx")
    lm("lda", V_HEAD)
    a.inc()
    a.op("and", imm=QN - 1)
    lm("sta", V_HEAD)
    a.plx()
    a.rts()

    # ── 글자 그림 읽기 → V_G[16] ─────────────────────────────────────────────────
    # 한글(V_IDX = 글리프 색인): 글리프 뱅크 32B/자(평면0·평면1 번갈아) → 평면0 만 16행
    a.label("vwf_ldg_h")
    a.rep(imm=0x20)
    lm("lda", V_IDX)
    for _ in range(5):
        a.asl()
    a.tax()
    a.sep(imm=0x20)
    a.phb()
    a.lda(imm=0x7E)
    a.pha()
    a.plb()
    a.ldy(imm=0x0000, m16=True)
    a.label("lgh_l")
    a.op("lda", addr=GLYPH_BASE, mode="longx")
    a.op("sta", addr=G16, mode="absy")
    a.inx()
    a.inx()
    a.iny()
    a.cpy(imm=0x0010, m16=True)
    a.bne(label="lgh_l")
    a.plb()
    a.rts()
    # 원본 1바이트 글자(V_VR = 코드): 훅 뱅크의 `rawtab` 16B/자
    a.label("vwf_ldg_r")
    a.rep(imm=0x20)
    lm("lda", V_VR)
    a.op("and", imm=0x00FF, m16=True)
    a.asl()
    a.asl()
    a.asl()
    a.asl()
    a.tax()
    a.sep(imm=0x20)
    a.phb()
    a.lda(imm=0x7E)
    a.pha()
    a.plb()
    a.ldy(imm=0x0000, m16=True)
    a.label("lgr_l")
    a.op("lda", addr="rawtab", mode="longx")
    a.op("sta", addr=G16, mode="absy")
    a.inx()
    a.iny()
    a.cpy(imm=0x0010, m16=True)
    a.bne(label="lgr_l")
    a.plb()
    a.rts()

    # 인게임 숫자(원판 시트 꼴, 왼쪽으로 한 칸 붙인 것): 훅 뱅크의 `numtab` 16B/자
    a.label("vwf_ldg_n")
    a.rep(imm=0x20)
    lm("lda", V_VR)
    a.op("and", imm=0x00FF, m16=True)
    a.asl()
    a.asl()
    a.asl()
    a.asl()
    a.tax()
    a.sep(imm=0x20)
    a.phb()
    a.lda(imm=0x7E)
    a.pha()
    a.plb()
    a.ldy(imm=0x0000, m16=True)
    a.label("lgn_l")
    a.op("lda", addr="numtab", mode="longx")
    a.op("sta", addr=G16, mode="absy")
    a.inx()
    a.iny()
    a.cpy(imm=0x0010, m16=True)
    a.bne(label="lgn_l")
    a.plb()
    a.rts()

    # 색이 바뀌는 자리 — 합성 칸이 반쯤 찬 상태면 칸 경계로 올린다(팔레트가 칸 단위라 한 칸에 두 색이 섞인다)
    a.label("vwf_csnap")
    a.phx()
    a.jsr(addr="vwf_sync", mode="abs")
    lm("lda", V_VO)
    a.beq(label="cs_done")
    a.rep(imm=0x20)
    lm("lda", V_VX)
    a.clc()
    a.op("adc", imm=7, m16=True)
    a.op("and", imm=0xFFF8, m16=True)
    lm("sta", V_VX)
    a.lsr()
    a.lsr()
    a.lsr()
    a.sep(imm=0x20)
    lm("sta", V_VCELL)
    a.label("cs_done")
    a.plx()
    a.rts()

    # 색 끝($E1) — 직전에 찍은 게 공백이 아니고 합성 칸이 반쯤 찬 채(이름 뒤 반각 A~D)면 조사가 칸을 나눠 쓰며 색이 번지니 칸 경계로 올린다
    a.label("vwf_cend")
    a.phx()
    a.jsr(addr="vwf_sync", mode="abs")
    lm("lda", V_VO)
    a.beq(label="ce_done")
    lm("lda", V_VR)
    a.cmp(imm=0x10)
    a.beq(label="ce_done")
    a.jsr(addr="vwf_csnap", mode="abs")
    a.label("ce_done")
    a.plx()
    a.rts()

    # 색 시작 토큰(X = $E2|$E3|$DC) — 칸 경계로 올리는 게 기본. 예외(관리자 (d) 안): 이름 뒤에 A~D(4px)가 붙어 색 구간이 8의 배수+4px 가 되고,
    # 바로 앞이 공백(칸 앞 절반, 잉크 없음)이면 올리지 않고 **그 칸의 색을 새 색으로 바꿔** 이름이 칸 중간에서 시작하게 둔다 —
    # 이름+글자가 칸 경계에서 끝나 조사가 흰 칸에서 시작한다. (엔진은 칸을 쓸 때마다 `$02:B07B` 로 타일맵 전체를 `$0349`(칸 색)에서 다시 만든다.)
    a.label("vwf_cstart")
    a.phx()
    a.phy()
    a.jsr(addr="vwf_sync", mode="abs")
    lm("lda", V_VO)
    a.beq(label="cst_snap")
    lm("lda", V_VR)
    a.cmp(imm=0x10)
    a.bne(label="cst_snap")
    a.cpx(imm=0x00DC, m16=True)
    a.bne(label="cst_nd")
    lm("lda", V_VO)  # 숫자 — 앞 공백이 반 칸(4)에서 끝났을 때만 그 칸 색을 바꿔 잇는다(「ＥＰ 1」 공백을 반각으로, 마스터 10-10)
    a.cmp(imm=0x04)
    a.bne(label="cst_snap")
    a.bra(label="cst_y0c")
    a.label("cst_nd")
    a.ldy(imm=0x0001, m16=True)
    a.op("lda", dp=0x3F, mode="indlongy")  # 다음 바이트 — {D6}(행위자)·{D7}(대상)
    a.cmp(imm=0xD6)
    a.beq(label="cst_d6")
    a.cmp(imm=0xD7)
    a.beq(label="cst_d7")
    a.label("cst_snap")
    a.jsr(addr="vwf_csnap", mode="abs")
    a.bra(label="cst_end")
    a.label("cst_d6")
    lm("lda", 0x000F3F)
    a.bpl(label="cst_snap")
    lm("lda", 0x000F43)
    a.bpl(label="cst_snap")
    a.bra(label="cst_yield")
    a.label("cst_d7")
    lm("lda", 0x000F40)
    a.bpl(label="cst_snap")
    lm("lda", 0x000F44)
    a.bpl(label="cst_snap")
    a.label("cst_yield")
    a.txa()
    a.cmp(imm=0xE3)
    a.beq(label="cst_y0c")
    a.lda(imm=0x04)  # $E2 = 색 $04
    a.bra(label="cst_yset")
    a.label("cst_y0c")
    a.lda(imm=0x0C)  # $E3 = 색 $0C
    a.label("cst_yset")
    a.pha()
    lm("lda", 0x00173B)  # 방금 쓴 칸(앞 공백이 든 칸)
    a.rep(imm=0x20)
    a.op("and", imm=0x00FF, m16=True)
    a.tax()
    a.sep(imm=0x20)
    a.pla()
    a.op("sta", addr=0x000349, mode="longx")
    a.label("cst_end")
    a.ply()
    a.plx()
    a.rts()

    # ── 커서를 V_VW 만큼 옮기고, 만든 칸이 68번째면 엔진의 줄 올림(−17칸 = −136px)을 따라간다 ──
    # 들어올 때 V_VNC = 이번에 **새로 만든 칸**의 번호
    a.label("vwf_adv")
    a.lda(imm=0x00)
    lm("sta", V_NLF)  # 줄 첫 글자가 나갔다 — 명시 개행 표지를 푼다
    a.rep(imm=0x20)
    lm("lda", V_VW)
    a.op("and", imm=0x00FF, m16=True)
    a.clc()
    a.op("adc", addr=V_VX, mode="long")
    lm("sta", V_VX)
    a.sep(imm=0x20)
    lm("lda", V_VNC)
    a.cmp(imm=0x44)
    a.bne(label="va_ok")
    a.rep(imm=0x20)
    lm("lda", V_VX)
    a.sec()
    a.op("sbc", imm=136, m16=True)
    lm("sta", V_VX)
    a.sep(imm=0x20)
    a.label("va_ok")
    a.rts()

    # ── 합성 칸에 글자를 얹는다 (V_G 에 그림, V_VW = 4|8, vwf_sync 를 마친 뒤) ───────────
    # 돌려줌: C=0 → A = 엔진에 줄 슬롯 코드 / C=1 → 삼킴(새 칸이 없다)
    a.label("vwf_put")
    lm("lda", V_VO)
    a.bne(label="vp_mid")
    # off=0 — 새 칸. 반각(4px)만 온다(8px 는 예전 길로 갔다)
    a.jsr(
        addr="vwf_flush", mode="abs"
    )  # 앞 칸이 바뀐 채 안 올라갔으면 지금 올린다(한 훅 호출 안에서 삼킨 글자가 이어졌을 때)
    a.jsr(addr="vwf_newslot", mode="abs")
    lm("sta", V_VS)
    a.jsr(addr="vwf_clrbuf", mode="abs")
    lm("lda", V_VS)
    lm("sta", V_VRSLOT)
    a.lda(imm=0x00)
    lm("sta", V_SH)
    a.jsr(addr="vwf_blitR", mode="abs")
    a.lda(imm=0x01)
    lm("sta", V_VD)
    lm("lda", V_VCELL)
    lm("sta", V_VNC)
    a.jsr(addr="vwf_adv", mode="abs")
    a.jmp(addr="vp_code", mode="abs")
    a.label("vp_mid")  # 칸 중간(열 1~7)에서 시작 — 들어가면 이 칸을 채우고, 넘치면 다음 칸으로 넘긴다
    lm("lda", V_VO)
    a.clc()
    a.op("adc", addr=V_VW, mode="long")
    a.cmp(imm=0x09)
    a.bcc(label="vp_fit")  # 시작 열 + 폭 ≤ 8
    a.jmp(addr="vp_spill", mode="abs")
    a.label("vp_fit")
    lm("lda", V_VS)
    lm("sta", V_VRSLOT)
    lm("lda", V_VO)
    lm("sta", V_SH)
    a.jsr(addr="vwf_blitR", mode="abs")
    a.lda(imm=0x01)
    lm("sta", V_VD)
    lm("lda", V_VW)
    a.rep(imm=0x20)
    a.op("and", imm=0x00FF, m16=True)
    a.clc()
    a.op("adc", addr=V_VX, mode="long")
    lm("sta", V_VX)
    a.sep(imm=0x20)
    a.sec()  # 새 칸 없음 → 삼킨다
    a.rts()
    a.label("vp_spill")  # 글자가 칸 경계를 넘는다: 앞 칸을 마저 채우고 새 칸을 연다
    lm("lda", V_VS)
    lm("sta", V_VRSLOT)
    lm("lda", V_VO)
    lm("sta", V_SH)
    a.jsr(addr="vwf_blitR", mode="abs")
    lm("lda", V_VS)
    a.jsr(addr="vwf_enq", mode="abs")  # 이 칸은 이제 끝났다 — 마지막 모양을 올린다
    a.jsr(addr="vwf_newslot", mode="abs")
    lm("sta", V_VS)
    a.jsr(addr="vwf_clrbuf", mode="abs")
    lm("lda", V_VS)
    lm("sta", V_VRSLOT)
    a.lda(imm=0x08)
    a.sec()
    a.op("sbc", addr=V_VO, mode="long")  # 다음 칸으로 넘치는 몫 = 8 − 시작 열
    lm("sta", V_SH)
    a.jsr(addr="vwf_blitL", mode="abs")
    a.lda(imm=0x01)
    lm("sta", V_VD)
    lm("lda", V_VCELL)
    a.inc()
    lm("sta", V_VNC)
    a.jsr(addr="vwf_adv", mode="abs")
    a.label("vp_code")
    lm("lda", V_VS)
    a.rep(imm=0x20)
    a.op("and", imm=0x00FF, m16=True)
    a.tax()
    a.sep(imm=0x20)
    a.op("lda", addr="slot_code", mode="absx")
    a.clc()
    a.rts()

    # ── 크롤 줄바꿈·쪽 바뀜: 지금 칸을 올리고 px 커서·칸 번호를 줄 처음으로 ──────────────────
    a.label("vwf_crawl_nl")
    a.jsr(addr="vwf_flush", mode="abs")
    a.rep(imm=0x20)
    a.lda(imm=0x0000, m16=True)
    lm("sta", V_VX)
    a.sep(imm=0x20)
    a.lda(imm=0xFF)
    lm("sta", V_OCELL)
    a.rts()

    # ── 훅을 나가기 전: 바뀐 지금 칸의 모양을 큐에 올린다 ───────────────────────────────
    a.label("vwf_flush")
    lm("lda", V_VD)
    a.beq(label="vf_ret")
    a.lda(imm=0x00)
    lm("sta", V_VD)
    lm("lda", V_VS)
    a.jsr(addr="vwf_enq", mode="abs")
    a.label("vf_ret")
    a.rts()

    # ── 줄 끝 칸 가장자리: 칸 중간(off=4)에 오는 8px 글자가 **줄 끝 칸**(16·33·50·67)에 걸치면 칸 경계로 올린다 ───────
    # 8px 글자가 off=4 에서 시작하면 오른쪽 절반은 이 칸에, 왼쪽 절반은 다음 칸에 들어간다. 그 다음 칸이 **다음 줄 첫 칸**이면
    # 글자가 반으로 갈려 줄 끝과 다음 줄머리에 반쪽씩 찍힌다(2026-10-09 C3 실기: 조각을 이어 붙인 로그에서 조각 끝 부호 뒤
    # 공백이 폭을 4px 어긋냈다). 문장 조각은 줄 처음에서 시작한다고 보고 조판했기 때문에 런타임에서만 알 수 있다.
    # ⇒ 이 칸의 남은 4px 는 비우고 px 커서를 다음 칸 경계(= 엔진이 다음에 쓸 칸 = 다음 줄 첫 칸)로 올려 예전 길로 보낸다.
    a.label("vwf_edge")
    lm("lda", V_VO)
    a.beq(label="ve_ret")
    a.clc()
    a.op("adc", addr=V_VW, mode="long")
    a.cmp(imm=0x09)
    a.bcc(label="ve_ret")  # 이 칸 안에 들어간다
    lm("lda", V_VCELL)
    a.cmp(imm=16)
    a.beq(label="ve_snap")
    a.cmp(imm=33)
    a.beq(label="ve_snap")
    a.cmp(imm=50)
    a.beq(label="ve_snap")
    a.cmp(imm=67)
    a.beq(label="ve_snap")
    a.label("ve_ret")
    a.rts()
    a.label("ve_snap")
    a.rep(imm=0x20)
    lm("lda", V_VX)
    a.clc()
    a.op("adc", imm=7, m16=True)
    a.op("and", imm=0xFFF8, m16=True)
    lm("sta", V_VX)
    a.lsr()
    a.lsr()
    a.lsr()
    a.sep(imm=0x20)
    lm("sta", V_VCELL)
    a.lda(imm=0x00)
    lm("sta", V_VO)
    a.rts()

    # ── 런타임 어절 줄바꿈: 공백 앞에서 「뒤따르는 낱말이 줄에 안 들어가면」 공백 대신 개행을 낸다 ─────────────────────
    # 전투 로그·시스템 메시지는 조각 하나가 한 문장이고 엔진이 **앞 조각 뒤에 이어 붙인다** — 조판기는 조각이 줄 처음에서 시작한다고
    # 보고 끊으므로 실제 줄 위치와 어긋나 엔진이 17칸에서 기계적으로 낱말 가운데를 끊었다(「1포/인트」·「지/혜가」, 번역 규칙 2-6).
    # 대본 스트림(`[$3F]`, 마지막으로 읽은 바이트를 가리킨다)을 **앞으로 읽어** 다음 공백·제어까지의 폭을 잰다:
    #   한글 2바이트 8px · 반각 부호(`.,!?`) 4px · 그 밖의 1바이트 8px · 사전 토큰 `$D0~$D5`(2바이트) 16 · 이름·도구·주문 `$D6~$DB·$DD` 24 ·
    #   수 `$DC` 16 · 색 `$E1~$E3` 0 · 그 밖의 제어는 낱말 끝. (런타임 값이라 어림이다 — 조판기의 후보 폭과 같은 눈금)
    # 줄 위치 px = (칸 번호 mod 17)×8 + 칸 안 위치. 공백 4px + 낱말 폭이 136 을 넘고 줄 첫머리가 아니면 C=1(개행).
    # 돌려줌: C=1 → 개행을 내라 · C=0 → 공백 그대로. A·X·Y 보존 안 함(호출자가 곧 덮는다) — X·Y 는 지킨다.
    a.label("vwf_wrapchk")
    a.phx()
    a.phy()
    a.jsr(addr="vwf_sync", mode="abs")
    lm("lda", V_WM)  # 문장 모드(`vwf_fitchk` 가 켠다)면 숫자 꼬리 규칙은 건너뛴다
    a.bne(label="wk_nn")
    lm("lda", V_VR)  # 바로 앞에 찍은 원판 글자가 숫자(0~9)면 그 뒤 공백은 줄바꿈 금지(「EP 1 포인트」가 숫자에서 갈리지 않게 — PS1 NOBREAK_SP 꼴)
    a.cmp(imm=0x11)  # 0~9 숫자 · 0x10 = 숫자 루틴이 덧붙이는 자리 패딩 공백(그 뒤 우리 공백도 같은 숫자 꼬리다)
    a.bcs(label="wk_nn")
    a.clc()
    a.jmp(addr="wk_fin", mode="abs")
    a.label("wk_nn")
    lm("lda", V_VCELL)
    a.label("wk_m")
    a.cmp(imm=17)
    a.bcc(label="wk_md")
    a.sec()
    a.sbc(imm=17)
    a.bra(label="wk_m")
    a.label("wk_md")
    a.asl()
    a.asl()
    a.asl()
    a.clc()
    a.op("adc", addr=V_VO, mode="long")
    a.bne(label="wk_go")
    a.clc()  # 줄 첫머리 — 넘길 곳이 없다
    a.jmp(addr="wk_fin", mode="abs")
    a.label("wk_go")
    a.rep(imm=0x20)
    a.op("and", imm=0x00FF, m16=True)
    lm("sta", V_T1)  # 줄 위치(문장 모드가 쓴다)
    a.sep(imm=0x20)
    lm("lda", V_WM)
    a.bne(label="wk_gs")
    a.rep(imm=0x20)
    lm("lda", V_T1)
    a.clc()
    a.op("adc", imm=4, m16=True)  # 공백
    lm("sta", V_T0)
    a.sep(imm=0x20)
    a.bra(label="wk_gd")
    a.label("wk_gs")  # 문장 모드는 공백이 없다
    a.rep(imm=0x20)
    lm("lda", V_T1)
    lm("sta", V_T0)
    a.sep(imm=0x20)
    a.label("wk_gd")
    a.ldy(imm=0x0001, m16=True)

    def addw(w):
        a.lda(imm=w)
        a.jsr(addr="wk_addw", mode="abs")

    a.label("wk_n")
    a.op("lda", dp=0x3F, mode="indlongy")
    a.cmp(imm=0x10)
    a.bne(label="wk_n1")
    a.jmp(addr="wk_sp", mode="abs")
    a.label("wk_n1")
    a.cmp(imm=0xCF)
    a.bcs(label="wk_nc")
    a.jmp(addr="wk_chr", mode="abs")
    a.label("wk_nc")
    a.cmp(imm=0xE1)
    a.bcc(label="wk_tok")  # $CF 개행 … $E0 : 낱말 끝이 아닌 $D0~$E0 중 토큰은 아래, 나머지는 끝
    a.cmp(imm=0xE4)
    a.bcc(label="wk_col")  # $E1~$E3 색 — 폭 0
    a.jmp(addr="wk_end", mode="abs")
    a.label("wk_col")
    a.iny()
    a.bra(label="wk_n")
    a.label("wk_tok")
    a.cmp(imm=0xD0)
    a.bcs(label="wk_t1")
    a.jmp(addr="wk_end", mode="abs")  # $CF 개행
    a.label("wk_t1")
    a.cmp(imm=0xD6)
    a.bcs(label="wk_rt")
    # 문장부호(. , ! ?) 바로 뒤의 사전 토큰은 대사 끝에 붙은 이름 꼬리다 — 낱말이 아니니 여기서 끝낸다(안 그러면 어림 32px 가 막줄 끝 낱말을 괜히 밀어 내린다)
    a.dey()
    a.op("lda", dp=0x3F, mode="indlongy")
    a.iny()
    for pc in (0x83, 0x84, 0x0C, 0x0F):
        a.cmp(imm=pc)
        a.bne(label=f"wk_dp{pc:02X}")
        a.jmp(addr="wk_end", mode="abs")
        a.label(f"wk_dp{pc:02X}")
    # 사전 토큰(코드+색인) — 실제 표기 폭을 표(`tw_d0`~`tw_d5`, 색인 하위 7비트)로 잰다. 색인 최상위 비트가 선 $D0(「파티 순서 n 번째」)만 32px 로 어림한다
    a.pha()
    a.iny()
    a.op("lda", dp=0x3F, mode="indlongy")
    a.dey()
    a.bpl(label="wk_dk")
    a.pla()
    addw(32)
    a.iny()
    a.iny()
    a.jmp(addr="wk_c", mode="abs")
    a.label("wk_dk")
    a.rep(imm=0x20)
    a.op("and", imm=0x007F, m16=True)
    a.tax()
    a.sep(imm=0x20)
    a.pla()  # 코드 $D0~$D5
    a.cmp(imm=0xD1)
    a.bcc(label="wk_d0t")
    a.beq(label="wk_d1t")
    a.cmp(imm=0xD3)
    a.bcc(label="wk_d2t")
    a.beq(label="wk_d3t")
    a.cmp(imm=0xD4)
    a.beq(label="wk_d4t")
    a.op("lda", addr="tw_d5", mode="absx")
    a.bra(label="wk_dte")
    a.label("wk_d0t")
    a.op("lda", addr="tw_d0", mode="absx")
    a.bra(label="wk_dte")
    a.label("wk_d1t")
    a.op("lda", addr="tw_d1", mode="absx")
    a.bra(label="wk_dte")
    a.label("wk_d2t")
    a.op("lda", addr="tw_d2", mode="absx")
    a.bra(label="wk_dte")
    a.label("wk_d3t")
    a.op("lda", addr="tw_d3", mode="absx")
    a.bra(label="wk_dte")
    a.label("wk_d4t")
    a.op("lda", addr="tw_d4", mode="absx")
    a.label("wk_dte")
    a.jsr(addr="wk_addw", mode="abs")
    a.iny()
    a.iny()
    a.jmp(addr="wk_c", mode="abs")
    a.label("wk_rt")
    a.cmp(imm=0xDC)
    a.beq(label="wk_num")
    a.cmp(imm=0xD6)
    a.beq(label="wk_d6")
    a.cmp(imm=0xD7)
    a.beq(label="wk_d7")
    addw(24)
    a.iny()
    a.jmp(addr="wk_c", mode="abs")
    a.label("wk_d6")  # 행위자 이름 — 실제 폭(표) + 같은 몬스터 여럿이면 뒤 글자(반각 4px)
    lm("lda", 0x000F3F)
    a.jsr(addr="wk_nm", mode="abs")
    a.jsr(addr="wk_addw", mode="abs")
    lm("lda", 0x000F3F)
    a.bpl(label="wk_d6e")
    lm("lda", 0x000F43)
    a.bpl(label="wk_d6e")
    addw(4)
    a.label("wk_d6e")
    a.iny()
    a.jmp(addr="wk_c", mode="abs")
    a.label("wk_d7")  # 대상 이름
    lm("lda", 0x000F40)
    a.jsr(addr="wk_nm", mode="abs")
    a.jsr(addr="wk_addw", mode="abs")
    lm("lda", 0x000F40)
    a.bpl(label="wk_d7e")
    lm("lda", 0x000F44)
    a.bpl(label="wk_d7e")
    addw(4)
    a.label("wk_d7e")
    a.iny()
    a.jmp(addr="wk_c", mode="abs")
    a.label("wk_num")
    addw(24)  # 숫자 치환 — 세 자리(피해 263)까지 잰다. 두 자리로 재면 「263 / 의」처럼 조사가 숫자에서 떨어진다
    a.iny()
    a.op("lda", dp=0x3F, mode="indlongy")  # 숫자 뒤 공백은 줄바꿈 금지 — 단위(「포인트」)까지 한 낱말로 잰다
    a.cmp(imm=0x10)
    a.bne(label="wk_nu")
    addw(4)
    a.iny()
    a.label("wk_nu")
    a.jmp(addr="wk_c", mode="abs")
    a.label("wk_chr")
    a.rep(imm=0x20)
    a.op("and", imm=0x00FF, m16=True)
    a.tax()
    a.sep(imm=0x20)
    a.op("lda", addr="lead_tab", mode="absx")
    a.cmp(imm=0xFF)
    a.beq(label="wk_raw")
    a.xba()  # A.low = 선두 서수 → B
    a.iny()
    a.op("lda", dp=0x3F, mode="indlongy")  # 색인 하위
    a.rep(imm=0x20)
    a.tax()  # X = 글리프 색인
    a.sep(imm=0x20)
    a.op("lda", addr="gw", mode="absx")  # 한글 8 · 영문은 잉크 폭
    a.jsr(addr="wk_addw", mode="abs")
    a.iny()
    a.jmp(addr="wk_c", mode="abs")
    a.label("wk_raw")
    a.cpx(imm=0x0083, m16=True)
    a.beq(label="wk_h")
    a.cpx(imm=0x0084, m16=True)
    a.beq(label="wk_h")
    a.cpx(imm=0x000C, m16=True)
    a.beq(label="wk_h")
    a.cpx(imm=0x000F, m16=True)
    a.beq(label="wk_h")
    addw(8)
    a.iny()
    a.jmp(addr="wk_c", mode="abs")
    a.label("wk_h")
    addw(4)
    a.iny()
    a.label("wk_c")
    a.cpy(imm=0x0030, m16=True)
    a.bcs(label="wk_end")
    a.jmp(addr="wk_n", mode="abs")
    a.label("wk_sp")  # 공백 — 낱말 모드면 낱말 끝, 문장 모드(`vwf_fitchk`)면 4px 로 치고 계속 간다
    lm("lda", V_WM)
    a.bne(label="wk_sp1")
    a.jmp(addr="wk_end", mode="abs")
    a.label("wk_sp1")
    addw(4)
    a.iny()
    a.jmp(addr="wk_c", mode="abs")
    a.label("wk_end")
    lm("lda", V_WM)
    a.beq(label="wk_ew")
    # 문장 모드: 줄 위치 V_T1 + 문장 폭 > 136 이고 문장만으로는 한 줄에 들면 C=1(새 줄에서 시작)
    a.rep(imm=0x20)
    lm("lda", V_T0)
    a.cmp(imm=137, m16=True)
    a.bcc(label="wk_esn")  # 이어 써도 들어간다
    a.sec()
    a.op("sbc", addr=V_T1, mode="long")  # 문장 폭
    a.cmp(imm=137, m16=True)
    a.bcs(label="wk_esn")  # 문장이 한 줄보다 길다 — 어절 개행에 맡긴다
    a.sec()
    a.sep(imm=0x20)
    a.bra(label="wk_fin")
    a.label("wk_esn")
    a.clc()
    a.sep(imm=0x20)
    a.bra(label="wk_fin")
    a.label("wk_ew")
    a.rep(imm=0x20)
    lm("lda", V_T0)
    a.cmp(imm=137, m16=True)  # C=1 ⇔ 공백+낱말이 136px 를 넘는다
    a.sep(imm=0x20)
    a.label("wk_fin")
    a.lda(imm=0x00)
    lm("sta", V_WM)  # 문장 모드를 끈다(C 는 그대로)
    a.ply()
    a.plx()
    a.rts()

    # ── 조각 첫머리 문장 줄 맞춤(번역 규칙 2-10) ─────────────────────────────────────────
    # 전투 로그는 조각 하나가 한 문장이고 엔진이 앞 조각 뒤에 이어 찍는다. 한 줄에 들어가는 문장을 두 줄로 쪼개지 않도록, **조각 첫머리에서**
    # 문장 끝($E0·$E4·개행)까지의 폭을 재서 줄 남은 칸에 안 들면(문장만으로는 한 줄에 드는데) 새 줄에서 시작한다. 폭 어림은 `vwf_wrapchk` 와 같다.
    # 돌려줌: C=1 → 개행을 먼저 내라 · C=0 → 그대로
    a.label("vwf_fitchk")
    a.lda(imm=0x01)
    lm("sta", V_WM)
    a.jsr(addr="vwf_wrapchk", mode="abs")  # 문장 모드 — 공백을 넘어 문장 끝까지 잰다(끝에서 모드가 꺼진다)
    a.rts()

    a.label("wk_nm")  # A = 이름 표 값(비트7 = 몬스터 · 아래 = 색인) → A = 그 이름의 폭(px). 표는 훅 뱅크 `tw_mon`·`tw_pty`(빌드가 사전 한글 표기로 잰다)
    a.cmp(imm=0x80)
    a.bcs(label="wk_nmm")
    a.op("and", imm=0x7F)
    a.rep(imm=0x20)
    a.op("and", imm=0x00FF, m16=True)
    a.tax()
    a.sep(imm=0x20)
    a.op("lda", addr="tw_pty", mode="absx")
    a.bra(label="wk_nme")
    a.label("wk_nmm")
    a.op("and", imm=0x7F)
    a.rep(imm=0x20)
    a.op("and", imm=0x00FF, m16=True)
    a.tax()
    a.sep(imm=0x20)
    a.op("lda", addr="tw_mon", mode="absx")
    a.label("wk_nme")
    a.rts()

    a.label("wk_addw")  # A = 폭(8비트) → V_T0(워드) += A
    a.rep(imm=0x20)
    a.op("and", imm=0x00FF, m16=True)
    a.clc()
    a.op("adc", addr=V_T0, mode="long")
    lm("sta", V_T0)
    a.sep(imm=0x20)
    a.rts()

    # ── 색 시작 앞 공백 폭 분산 ───────────────────────────────────────────────────────
    # 색(노랑 이름·숫자)은 8px 칸 단위라 색 구간은 칸 경계에서 시작해야 한다. 앞 글이 반 칸에서 끝나면 4px 를 어디선가 메워야 하는데, 전부 한 공백에
    # 몰면 「일격!   슬라임」처럼 전각 틈이 된다(마스터 10-10). 이 공백에서 **다음 색 시작($E2·$E3·$DC)까지** 대본을 훑어(폭을 아는 글자만),
    # 남는 틈(0~7px)을 그 사이 공백 k 개에 나눈다 — 이 공백이 올림(ceil(틈/k))만큼 더 넓어진다. 모르는 토큰(이름 등)이 끼면 안 한다.
    # 나갈 때 V_SPX = 이 공백의 추가 폭(0~7).
    a.label("vwf_spgap")
    a.phx()
    a.phy()
    a.jsr(addr="vwf_sync", mode="abs")
    lm("lda", V_VO)
    a.rep(imm=0x20)
    a.op("and", imm=0x00FF, m16=True)
    a.clc()
    a.op("adc", imm=4, m16=True)  # 합 = 커서 칸 안 위치 + 이 공백
    lm("sta", V_T0)
    a.sep(imm=0x20)
    a.lda(imm=0x01)
    lm("sta", V_T1)  # k = 공백 수
    a.ldy(imm=0x0001, m16=True)

    def sgw(w):
        a.lda(imm=w)
        a.jsr(addr="wk_addw", mode="abs")

    a.label("sg_n")
    a.cpy(imm=0x0030, m16=True)
    a.bcc(label="sg_n0")
    a.jmp(addr="sg_none", mode="abs")
    a.label("sg_n0")
    a.op("lda", dp=0x3F, mode="indlongy")
    a.cmp(imm=0x10)
    a.bne(label="sg_1")
    sgw(4)
    lm("lda", V_T1)
    a.inc()
    lm("sta", V_T1)
    a.iny()
    a.bra(label="sg_n")
    a.label("sg_1")
    a.cmp(imm=0xDC)
    a.beq(label="sg_found")
    a.cmp(imm=0xE2)
    a.beq(label="sg_found")
    a.cmp(imm=0xE3)
    a.beq(label="sg_found")
    a.cmp(imm=0xCF)
    a.bcc(label="sg_chr")
    a.jmp(addr="sg_none", mode="abs")
    a.label("sg_chr")
    a.rep(imm=0x20)
    a.op("and", imm=0x00FF, m16=True)
    a.tax()
    a.sep(imm=0x20)
    a.op("lda", addr="lead_tab", mode="absx")
    a.cmp(imm=0xFF)
    a.beq(label="sg_raw")
    sgw(8)  # 한글 — 선두 + 색인 두 바이트
    a.iny()
    a.iny()
    a.bra(label="sg_n")
    a.label("sg_raw")
    a.cpx(imm=0x0083, m16=True)
    a.beq(label="sg_h")
    a.cpx(imm=0x0084, m16=True)
    a.beq(label="sg_h")
    a.cpx(imm=0x000C, m16=True)
    a.beq(label="sg_h")
    a.cpx(imm=0x000F, m16=True)
    a.beq(label="sg_h")
    sgw(8)
    a.iny()
    a.bra(label="sg_n")
    a.label("sg_h")
    sgw(4)
    a.iny()
    a.bra(label="sg_n")
    a.label("sg_found")
    # 목표 위치: 칸 경계(0). 다만 이름 뒤에 반각 글자(A~D)가 붙을 이름이면 **칸 중간(4)** 에 둔다 — 이름+글자가 칸 경계에서 끝나게
    # (`vwf_cstart` 가 앞 공백 칸의 색을 바꿔 이어받는다).
    a.cmp(imm=0xDC)
    a.beq(label="sg_let")  # 숫자도 칸 중간(4)에서 시작 — 앞 공백이 반각 그대로
    a.iny()
    a.op("lda", dp=0x3F, mode="indlongy")
    a.cmp(imm=0xD6)
    a.beq(label="sg_l6")
    a.cmp(imm=0xD7)
    a.beq(label="sg_l7")
    a.bra(label="sg_nl")
    a.label("sg_l6")
    lm("lda", 0x000F3F)
    a.bpl(label="sg_nl")
    lm("lda", 0x000F43)
    a.bpl(label="sg_nl")
    a.bra(label="sg_let")
    a.label("sg_l7")
    lm("lda", 0x000F40)
    a.bpl(label="sg_nl")
    lm("lda", 0x000F44)
    a.bpl(label="sg_nl")
    a.label("sg_let")
    a.lda(imm=0x04)
    a.bra(label="sg_go")
    a.label("sg_nl")
    a.lda(imm=0x00)
    a.label("sg_go")
    lm("sta", k["V_SPX"])  # 임시: 목표 위치
    a.rep(imm=0x20)
    lm("lda", V_T0)
    a.op("and", imm=0x0007, m16=True)
    lm("sta", V_T0)  # r = 합 mod 8
    a.sep(imm=0x20)
    lm("lda", k["V_SPX"])
    a.sec()
    a.op("sbc", addr=V_T0, mode="long")
    a.op("and", imm=0x07)  # 틈 s = (8 - r) mod 8
    lm("sta", V_T0)
    a.ldx(imm=0x0000, m16=True)
    a.lda(imm=0x00)
    a.label("sg_c")
    a.op("cmp", addr=V_T0, mode="long")
    a.bcs(label="sg_d")
    a.inx()
    a.clc()
    a.op("adc", addr=V_T1, mode="long")
    a.bra(label="sg_c")
    a.label("sg_d")
    a.txa()
    a.bra(label="sg_set")
    a.label("sg_none")
    a.lda(imm=0x00)
    a.label("sg_set")
    lm("sta", k["V_SPX"])
    a.ply()
    a.plx()
    a.rts()

    # ── 입구 1: 한글 글리프(V_IDX) ────────────────────────────────────────────────
    # 돌려줌: C=0 → A = 엔진에 줄 코드 · C=1 → 삼킴(한글은 8px 라 삼키는 일은 없다)
    a.label("vwf_glyph")
    a.jsr(addr="vwf_sync", mode="abs")
    a.lda(imm=0xFF)
    lm("sta", V_VR)  # 한글이 찍히면 「직전 원판 글자」는 없다
    a.rep(imm=0x20)
    lm("lda", k["V_IDX"])
    a.tax()
    a.sep(imm=0x20)
    a.op("lda", addr="gw", mode="absx")  # 이 글리프의 진행 폭(px) — 대개 8, 영문은 잉크 폭
    lm("sta", V_VW)
    a.jsr(addr="vwf_edge", mode="abs")
    lm("lda", V_VW)
    a.cmp(imm=0x08)
    a.bne(label="vg_mis")  # 좁은 글리프는 칸을 이웃과 나눠 쓴다 — 합성 칸으로
    lm("lda", V_VO)
    a.bne(label="vg_mis")
    a.jsr(addr="alloc", mode="abs")  # 칸 시작의 8px — 예전 길(글리프 캐시)
    lm("sta", V_VCODE)
    lm("lda", V_VCELL)
    lm("sta", V_VNC)
    a.lda(imm=0x08)
    lm("sta", V_VW)
    a.jsr(addr="vwf_adv", mode="abs")
    lm("lda", V_VCODE)
    a.clc()
    a.rts()
    a.label("vg_mis")
    a.jsr(addr="vwf_ldg_h", mode="abs")
    a.jmp(addr="vwf_put", mode="abs")

    # ── 입구 2: 원본 1바이트 글자(X = 코드 < $CF) ─────────────────────────────────
    a.label("vwf_raw")
    a.txa()
    lm("sta", V_VR)
    a.jsr(addr="vwf_sync", mode="abs")
    # 오프닝·엔딩(컨텍스트 1)의 숫자는 **늘 우리 글꼴 4px 반각 합성**으로(마스터 10-08 「얇은 반각이 더 일관성 있다」). 칸 시작이면 원판 시트의
    # 굵은 숫자 타일이, 칸 중간이면 합성 칸의 가는 숫자가 나가 한 문장 안에서 꼴이 섞였고 「1 0」 처럼 벌어졌다. 인게임(0)은 그대로.
    lm("lda", V_VR)
    a.cmp(imm=0x0A)
    a.bcs(label="vr_nd")
    lm("lda", V_CTX)
    a.cmp(imm=0x01)
    a.bne(label="vr_n2")
    a.jsr(addr="vwf_ldg_r", mode="abs")
    a.lda(imm=0x04)
    lm("sta", V_VW)  # 우리 글꼴 숫자(4px 폭)를 반각 칸으로 — 「10」이 붙는다
    a.jmp(addr="vwf_put", mode="abs")
    a.label("vr_n2")  # 인게임: 숫자 치환(`{DC}` 등 — 임시 문자열 모드 `$1773`≠0)으로 찍히는 숫자는 원판 꼴 그대로 8px 합성 — 칸 시작이면 8px·중간이면 얇은 4px 로 섞여 「2 9」로 벌어지고 색이 갈렸다(마스터 10-09 규칙 1-5)
    a.op("lda", addr=0x001773, mode="long")
    a.beq(label="vr_nd")
    a.jsr(addr="vwf_ldg_n", mode="abs")
    a.lda(imm=0x08)
    lm("sta", V_VW)
    a.jsr(addr="vwf_edge", mode="abs")
    a.jmp(addr="vwf_put", mode="abs")
    a.label("vr_nd")
    lm("lda", V_VR)
    a.cmp(imm=0x10)
    a.bne(label="vr_nsp")
    a.jmp(addr="vr_sp", mode="abs")
    a.label("vr_nsp")
    for code in HALF_CODES[1:] + LETTER_CODES:
        a.cmp(imm=code)
        a.beq(label="vr_h1")
    lm("lda", V_VO)
    a.bne(label="vr_fm")
    a.label("vr_pass")  # 칸 시작의 8px 원본 글자 — 그대로 내준다(타일은 시트에 있다)
    lm("lda", V_VCELL)
    lm("sta", V_VNC)
    a.lda(imm=0x08)
    lm("sta", V_VW)
    a.jsr(addr="vwf_adv", mode="abs")
    lm("lda", V_VR)
    a.clc()
    a.rts()
    a.label("vr_h1")  # `beq` 가 멀어 가까운 징검다리를 둔다
    a.jmp(addr="vr_half", mode="abs")
    a.label("vr_fm")  # 칸 중간에 오는 8px 원본 글자 — 그림이 있으면 합성, 없으면 칸 경계로 맞춘다
    a.lda(imm=0x08)
    lm("sta", V_VW)
    a.jsr(addr="vwf_edge", mode="abs")  # 줄 끝 칸이면 칸 경계로 올라가 off=0 이 된다
    lm("lda", V_VO)
    a.bne(label="vr_fm2")
    a.jmp(addr="vr_pass", mode="abs")
    a.label("vr_fm2")
    lm("lda", V_VR)
    a.rep(imm=0x20)
    a.op("and", imm=0x00FF, m16=True)
    a.tax()
    a.sep(imm=0x20)
    a.op("lda", addr="rawvalid", mode="absx")
    a.beq(label="vr_snap")
    a.jsr(addr="vwf_ldg_r", mode="abs")
    a.lda(imm=0x08)
    lm("sta", V_VW)
    a.jmp(addr="vwf_put", mode="abs")
    a.label("vr_snap")
    a.rep(imm=0x20)
    lm("lda", V_VX)
    a.clc()
    a.op("adc", imm=7, m16=True)
    a.op("and", imm=0xFFF8, m16=True)
    lm("sta", V_VX)
    a.lsr()
    a.lsr()
    a.lsr()
    a.sep(imm=0x20)
    lm("sta", V_VCELL)
    a.jmp(addr="vr_pass", mode="abs")
    a.label(
        "vr_sp"
    )  # 공백 — 줄 첫 칸이면 건너뛴다(마스터 판정 2026-09-27④). 크롤은 손으로 맞춘 줄이라 건너뛰지 않는다
    lm("lda", V_VO)
    a.bne(label="vr_hfar")
    lm("lda", V_OPEN)
    a.bne(label="vr_hfar")
    lm("lda", V_NLF)
    a.beq(label="vr_sp2")
    a.label("vr_hfar")
    a.jmp(addr="vr_half", mode="abs")
    a.label("vr_sp2")
    lm("lda", V_VT)
    a.beq(label="vr_skip")
    a.cmp(imm=17)
    a.beq(label="vr_skip")
    a.cmp(imm=34)
    a.beq(label="vr_skip")
    a.cmp(imm=51)
    a.beq(label="vr_skip")
    a.label("vr_half")
    a.jsr(addr="vwf_ldg_r", mode="abs")
    a.lda(imm=0x04)
    lm("lda", V_VR)
    a.cmp(imm=0x10)
    a.bne(label="vh_go")
    lm("lda", V_OPEN)
    a.bne(label="vh_go")
    lm("lda", k["V_SPX"])  # 색 시작 앞 공백이면 틈을 나눠 가진다(`vwf_spgap`)
    a.clc()
    a.adc(imm=0x04)
    a.bra(label="vh_set")
    a.label("vh_go")
    a.lda(imm=0x04)
    a.label("vh_set")
    lm("sta", V_VW)
    a.jsr(addr="vwf_edge", mode="abs")  # 반각도 줄 끝 칸에서 걸치면 다음 줄로
    a.jmp(addr="vwf_put", mode="abs")
    a.label("vr_skip")
    a.sec()
    a.rts()


def rawtab(tbl: dict[str, int], render) -> tuple[bytes, bytes]:
    """원본 1바이트 코드(0..$CE) → 16B 1bpp 그림 표(`rawtab`)와 「그림이 있나」 표(`rawvalid`, 256B).
    `tbl` = {글자: 코드}(인코더의 `KR_TABLE`), `render(ch)` = 16행 정수 목록."""
    pics = {}
    for ch, code in tbl.items():
        if code >= 0xCF or ch == "\n":
            continue
        pics[code] = bytes(render(ch)) if ch != " " else bytes(16)
    rt = bytearray(0xCF * 16)
    valid = bytearray(256)
    for code, pic in pics.items():
        rt[code * 16 : code * 16 + 16] = pic
        valid[code] = 1
    return bytes(rt), bytes(valid)
